control 'V-92677' do
  title "The Apache web server must invalidate session identifiers upon hosted
application user logout or other session termination."
  desc  "Captured sessions can be reused in \"replay\" attacks. This
requirement limits the ability of adversaries from capturing and continuing to
employ previously valid session IDs.

    Session IDs are tokens generated by web applications to uniquely identify
an application user's session. Unique session IDs help to reduce predictability
of said identifiers. When a user logs out, or when any other session
termination event occurs, the web server must terminate the user session to
minimize the potential for an attacker to hijack that particular user session.


  "
  desc  'rationale', ''
  desc  'check', "
    Determine the location of the \"HTTPD_ROOT\" directory and the
\"httpd.conf\" file:

    # httpd -V | egrep -i 'httpd_root|server_config_file'
    -D HTTPD_ROOT=\"/etc/httpd\"
    -D SERVER_CONFIG_FILE=\"conf/httpd.conf\"

    Search for the following directive:

    \"SessionMaxAge\"

    # cat /<path_to_file>/httpd.conf | grep -i \"SessionMaxAge\"

    Verify the value of \"SessionMaxAge\" is set to \"600\" or less.

    If the \"SessionMaxAge\" does not exist or is set to more than \"600\",
this is a finding.
  "
  desc 'fix', "
    Determine the location of the \"HTTPD_ROOT\" directory and the
\"httpd.conf\" file:

    # httpd -V | egrep -i 'httpd_root|server_config_file'
    -D HTTPD_ROOT=\"/etc/httpd\"
    -D SERVER_CONFIG_FILE=\"conf/httpd.conf\"

    Add the following line to the \"httpd.conf\" file:

    SessionMaxAge 600

    Restart Apache: apachectl restart
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000220-WSR-000201'
  tag satisfies: %w(SRG-APP-000220-WSR-000201 SRG-APP-000295-WSR-000012)
  tag gid: 'V-92677'
  tag rid: 'SV-102765r1_rule'
  tag stig_id: 'AS24-U1-000460'
  tag fix_id: 'F-98919r1_fix'
  tag cci: %w(CCI-001185 CCI-002361)
  tag nist: ['SC-23 (1)', 'AC-12']

  config_path = input('config_path')

  describe apache_conf(config_path) do
    its('SessionMaxAge') { should_not be_nil }
  end

  unless apache_conf(config_path).SessionMaxAge.nil?
    apache_conf(config_path).SessionMaxAge.each do |value|
      describe 'SessionMaxAge value should be less than or equal to 600' do
        subject { value }
        it { should be <= 600 }
      end
    end
  end
end
